name: print_device
run-name: ${{ github.actor }} is printing device
on: [push, pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    steps:
      - name: list
        run: |
          ls -al
          df -h


